title: Aero Chronicles
description: Aerospace Engineering documentation
theme: just-the-docs

url: https://AircraftAnorak.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
